### ISSUE TITLE
Incomplete list of exposed types to create custom animations

### ISSUE THREAD

**Issue by m-sadegh-sh** [DanielCardonaRojas/flickered_cards#2]
Let me thank you for creating such a well-crafted package. ❤❤❤

I wanted to create a customized version of the DeckAnimation and one of the requirements is to change the count of visible cards. Based on the source code, I need to change `LayoutConfig.cardsBefore` to a different value, let's say 4, but as this type isn't in the list of exposed types, I couldn't override the `layoutConfig` property to return a different `LayoutConfig` instance. This is the same for the `AnimationConfig` type.

**Comment by DanielCardonaRojas** [comment]
Hi @m-sadegh-sh  thanks for reporting this, I have published a new version adding the missing export, let me know if anything else comes up.
